stages:
  - lint
  - test
  - security
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - build/

linters:
  image: node:lts
  stage: lint
  script:
    - npm install
    - npm run lint
    - npm run solhint
  allow_failure: true

test:
  image: node:lts
  stage: test
  script:
    # node_modules inherited from pipeline cache
    - apt-get update && apt-get install -y gawk
    - npm run compile
    - npm run coverage
    # Flatten out the contracts for symbolic analysis
    - npm run flatten
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage
      - flatten.sol
    expire_in: 10 days
    reports:
      cobertura: coverage/cobertura-coverage.xml

mythril:
  image: sharathkumaranbu/mythril-ci
  stage: security
  script:
    # From artifacts
    - myth -x flatten.sol

slither:
  image: python
  stage: security
  before_script:
    - pip3 install slither-analyzer
  script:
    - slither .
